version: 0.0
os: linux
files:
  - source: /apache.conf_
    destination: /etc/httpd/conf/
  - source: /apache_logs.conf
    destination: /etc/awslogs/config
  - source: /index.html
    destination: /var/www/html/
#index.html
hooks:
  BeforeInstall:
    - location: scripts/create_backup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_apache.sh
      timeout: 300
      runas: root